spring:
  profiles:
    active: local
  application:
    name: resource-server-flights

# Profile: local
---
spring:
  profiles: local
  jackson:
    serialization:
      indent_output: true

server:
  port: 9010

management:
  security:
    enabled: false
  context-path: /actuator

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/auth/me
      tokenInfoUri: http://localhost:8080/auth/oauth/check_token
    client:
      client-id: flights
      client-secret: flightssecret

logging:
  level:
    com.kmejka: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.web.util.matcher: INFO