spring:
  profiles:
    active: local
  application:
    name: client

# Profile: local
---
spring:
  profiles: local
  jackson:
    serialization:
      indent_output: true

server:
  port: 8090

management:
  security:
    enabled: false
  context-path: /actuator

service:
  bookings-api:
    service-name: bookings-api
    service-address: http://localhost:9000/api/bookings/v1

logging:
  level:
    com.kmejka: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.web.util.matcher: INFO

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
      scope: read-flights, read-bookings
    resource:
      user-info-uri: http://localhost:8080/auth/user